print("Hello World")
print("Jhon")
print("Jhon Kennedy")
print("Hi, I am Python.")
print(25)
print(2*2)
print("2+5+9")
print("Hllo, ","I ","am ","Jhon. ")
print("Jhon ","is ",20, " Years ","old.")
print(5,"+",4,"=",5+4)
